# 使用 Ubuntu 作为基础镜像
FROM ubuntu:latest

# 更新软件包列表并安装 SSH 服务器
RUN apt-get update \
    && apt-get install -y openssh-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# 启用 SSH 登录
RUN mkdir /var/run/sshd
RUN echo 'root:cizai.io' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH 登录配置
RUN sed -ri 's/^#?PasswordAuthentication\s+.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -ri 's/^#?PermitEmptyPasswords\s+.*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
RUN sed -ri 's/^#?UsePAM\s+.*/UsePAM no/' /etc/ssh/sshd_config

# 开放 SSH 端口
EXPOSE 22

# 启动 SSH 服务器
CMD ["/usr/sbin/sshd", "-D"]
